/**
 * Renders the quiz + play/divergence results into the three output shapes
 * diffquiz produces: a markdown PR comment, a compact terminal summary, and
 * the --print spoiler view. Markdown must stay plain, ASCII-safe GFM — it
 * gets pasted into PR comments, so no ANSI codes ever end up in it.
 */
import type { DiffRef, DivergenceReport, Quiz, QuizQuestion, QuizResult } from "./types.ts";
import { bold, dim, green, red, yellow } from "./ansi.ts";

export interface ReportMeta {
  baseDescription: string;
  provider: string;
  model?: string;
  truncated: boolean;
  version: string;
}

function formatRefs(refs: DiffRef[]): string {
  if (refs.length === 0) return "none";
  return refs.map((r) => `${r.file}:${r.lines.join(",")}`).join(", ");
}

function questionSummaryLine(q: QuizQuestion, index: number): string {
  return `Q${index + 1} [${q.kind}] ${q.question}`;
}

// ---------------------------------------------------------------------------
// Markdown (PR comment)
// ---------------------------------------------------------------------------

function markdownQuestionBlock(
  result: QuizResult | null,
  q: QuizQuestion,
  index: number,
): string {
  const lines: string[] = [];
  const answer = result?.answers[index];
  const badge = result === null ? "" : answer?.correct ? " ✅" : answer?.chosenIndex === null ? " ⚪" : " ❌";
  lines.push(`<details>`);
  lines.push(`<summary>${questionSummaryLine(q, index)}${badge}</summary>`);
  lines.push("");
  if (result !== null && answer !== undefined) {
    const chosenText = answer.chosenIndex === null ? "_not answered_" : q.options[answer.chosenIndex];
    lines.push(`- Chosen: ${chosenText}`);
  }
  lines.push(`- Correct: ${q.options[q.correctIndex]}`);
  lines.push(`- Explanation: ${q.explanation}`);
  lines.push(`- Refs: ${formatRefs(q.diffRefs)}`);
  lines.push("");
  lines.push(`</details>`);
  return lines.join("\n");
}

function markdownDivergenceSection(quiz: Quiz, divergence: DivergenceReport): string {
  const lines: string[] = [];
  lines.push(`### ⚠️ Divergence check`);
  lines.push("");
  lines.push(`${divergence.runs.length} independent answer run(s).`);
  lines.push("");
  if (divergence.flaggedQuestionIds.length === 0) {
    lines.push(`No questions flagged — independent runs agreed.`);
    return lines.join("\n");
  }
  for (const qid of divergence.flaggedQuestionIds) {
    const qIndex = quiz.questions.findIndex((q) => q.id === qid);
    const question = qIndex >= 0 ? quiz.questions[qIndex] : undefined;
    const perQ = divergence.perQuestion.find((p) => p.questionId === qid);
    const label = question ? questionSummaryLine(question, qIndex) : qid;
    const distinct = perQ?.distinctAnswers.length ?? 0;
    lines.push(`- **${label}** — runs disagreed (${distinct} distinct answers); this question may be ambiguous rather than the diff being unclear.`);
  }
  return lines.join("\n");
}

export function renderMarkdown(
  quiz: Quiz,
  result: QuizResult | null,
  divergence: DivergenceReport | null,
  meta: ReportMeta,
): string {
  const total = quiz.questions.length;
  const lines: string[] = [];

  if (result !== null) {
    const seconds = Math.round(result.durationMs / 1000);
    lines.push(`### 🎯 diffquiz — ${result.correctCount}/${total} on this diff (${seconds}s)`);
  } else {
    lines.push(`### 🎯 diffquiz — ${total} question${total === 1 ? "" : "s"} on this diff`);
  }
  lines.push(`> Non-blocking self-check: did the author read what they're merging?`);
  lines.push("");

  quiz.questions.forEach((q, i) => {
    lines.push(markdownQuestionBlock(result, q, i));
    lines.push("");
  });

  if (divergence !== null) {
    lines.push(markdownDivergenceSection(quiz, divergence));
    lines.push("");
  }

  lines.push(`---`);
  const providerLabel = meta.model ? `${meta.provider} (${meta.model})` : meta.provider;
  const footerParts = [
    `Generated by diffquiz v${meta.version} via ${providerLabel}.`,
    `Diff vs ${meta.baseDescription}.`,
  ];
  if (meta.truncated) {
    footerParts.push(`Note: the diff was truncated to fit the size budget — some changes were not shown to the model.`);
  }
  lines.push(footerParts.join(" "));

  return lines.join("\n").trimEnd() + "\n";
}

// ---------------------------------------------------------------------------
// Terminal (compact colored summary)
// ---------------------------------------------------------------------------

export function renderTerminal(quiz: Quiz, result: QuizResult, meta: ReportMeta): string {
  const total = quiz.questions.length;
  const seconds = Math.round(result.durationMs / 1000);
  const lines: string[] = [];
  lines.push(bold(`diffquiz — ${result.correctCount}/${total} in ${seconds}s`));
  const badges = quiz.questions.map((q, i) => {
    const answer = result.answers[i];
    const mark = answer?.correct ? green("✓") : answer?.chosenIndex === null ? yellow("○") : red("✗");
    return `${mark} ${dim(q.id)}`;
  });
  lines.push(badges.join("  "));
  const providerLabel = meta.model ? `${meta.provider} (${meta.model})` : meta.provider;
  lines.push(dim(`via ${providerLabel} · diff vs ${meta.baseDescription}`));
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// --print spoiler view
// ---------------------------------------------------------------------------

export function renderPrint(quiz: Quiz): string {
  const total = quiz.questions.length;
  const lines: string[] = [];
  lines.push(bold(`diffquiz — ${total} question${total === 1 ? "" : "s"} (spoiler view)`));
  quiz.questions.forEach((q, i) => {
    lines.push("");
    lines.push(`${dim(`[${q.kind}]`)} ${bold(`${i + 1}) ${q.question}`)}`);
    const letters = ["1", "2", "3", "4"];
    q.options.forEach((opt, oi) => {
      const mark = oi === q.correctIndex ? green(" ✔") : "";
      lines.push(`  ${letters[oi]}) ${opt}${mark}`);
    });
    lines.push(dim(q.explanation));
    const refs = formatRefs(q.diffRefs);
    if (refs !== "none") {
      lines.push(dim(`See: ${refs}`));
    }
  });
  return lines.join("\n");
}
